const MODIFICA_TITULO = "MODIFICA_TITULO";
const MODIFICA_DESCRICAO = "MODIFICA_DESCRICAO";
const MODIFICA_DONE = "MODIFICA_DONE";
const MODIFICA_BUSCA = "MODIFICA_BUSCA";
const MODIFICA_LISTA = "MODIFICA_LISTA";
const EDITA_TODO = "EDITA_TODO";
const CLEAR_ALL = "CLEAR_ALL";
export {
    MODIFICA_TITULO,
    MODIFICA_DESCRICAO,
    MODIFICA_DONE,
    MODIFICA_BUSCA,
    MODIFICA_LISTA,
    EDITA_TODO,
    CLEAR_ALL
}